// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice = HeroWithCtaImageAndHighlightTextSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *Hero → With Highlight & Supporting Text → Primary → Highlight Callouts*
 */
export interface HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingTextPrimaryCalloutsItem {
  /**
   * Callout Text field in *Hero → With Highlight & Supporting Text → Primary → Highlight Callouts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta_image_and_highlight_text.with_highlight_and_supporting_text.primary.callouts[].callout_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  callout_text: prismic.KeyTextField;

  /**
   * Highlight field in *Hero → With Highlight & Supporting Text → Primary → Highlight Callouts*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta_image_and_highlight_text.with_highlight_and_supporting_text.primary.callouts[].highlight
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight: prismic.BooleanField;
}

/**
 * Primary content in *Hero → With Highlight & Supporting Text → Primary*
 */
export interface HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingTextPrimary {
  /**
   * Main Title field in *Hero → With Highlight & Supporting Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta_image_and_highlight_text.with_highlight_and_supporting_text.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → With Highlight & Supporting Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta_image_and_highlight_text.with_highlight_and_supporting_text.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Supporting Description field in *Hero → With Highlight & Supporting Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta_image_and_highlight_text.with_highlight_and_supporting_text.primary.supporting_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  supporting_text: prismic.RichTextField;

  /**
   * Highlight Callouts field in *Hero → With Highlight & Supporting Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta_image_and_highlight_text.with_highlight_and_supporting_text.primary.callouts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  callouts: prismic.GroupField<
    Simplify<HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingTextPrimaryCalloutsItem>
  >;

  /**
   * Primary Call to Action field in *Hero → With Highlight & Supporting Text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta_image_and_highlight_text.with_highlight_and_supporting_text.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * With Highlight & Supporting Text variation for Hero Slice
 *
 * - **API ID**: `with_highlight_and_supporting_text`
 * - **Description**: This variation includes a main title, subtitle, callouts with optional highlight, background/supporting image, supporting description, and a main CTA button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingText =
  prismic.SharedSliceVariation<
    "with_highlight_and_supporting_text",
    Simplify<HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingTextPrimary>,
    never
  >;

/**
 * Slice variation for *Hero*
 */
type HeroWithCtaImageAndHighlightTextSliceVariation =
  HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingText;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_with_cta_image_and_highlight_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithCtaImageAndHighlightTextSlice = prismic.SharedSlice<
  "hero_with_cta_image_and_highlight_text",
  HeroWithCtaImageAndHighlightTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroWithCtaImageAndHighlightTextSlice,
      HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingTextPrimaryCalloutsItem,
      HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingTextPrimary,
      HeroWithCtaImageAndHighlightTextSliceVariation,
      HeroWithCtaImageAndHighlightTextSliceWithHighlightAndSupportingText,
    };
  }
}
