import type { Metadata } from "next";
import { Anton, Inter } from "next/font/google";
import "./globals.css";
import PageTransition from "../components/PageTransition";
import PageLoader from "../components/PageLoader";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const anton = Anton({
  variable: "--font-anton",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${anton.variable} ${inter.className} antialiased`}
      > 
        <PageTransition>
         <PageLoader />

         {children}
        </PageTransition>
      </body>
    </html>
  );
}
